#!/bin/bash -ex

INSTALL_DIR=$PWD/libunwind_install

LIB_VERSION="1.7.2"
libunwind=./libunwind-${LIB_VERSION}.tar.gz
if [[ ! -f "${libunwind}" ]]; then
    wget -O ${libunwind} https://github.com/libunwind/libunwind/releases/download/v${LIB_VERSION}/libunwind-${LIB_VERSION}.tar.gz
fi
rm -rf libunwind-${LIB_VERSION}
tar xfv ${libunwind}

cd libunwind-${LIB_VERSION}

if [[ -f "autogen.sh" ]]; then
    ./autogen.sh 
else
    autoreconf -i
fi

./configure --prefix=$INSTALL_DIR
make -j 8
rm -rf $INSTALL_DIR
make install
